#!/usr/bin/env bash

#echo '  ▀▀'
#echo '  ██ █▀██ █▀█▀██'
#echo '  ██ █▄██ █ █ ██'
#echo ' ▀▀▀ ▀'

mkdir node_modules
cd node_modules
git clone --depth=1 git://github.com/chjj/blessed
git clone --depth=1 git://github.com/websockets/ws
git clone --depth=1 git://github.com/heineiuo/isomorphic-ws
